library(FSelector)
setwd("C:/Pradeep/Working Set/Consulting/Kaggle/DataSciencePrep/InsofeChap1/Data")
entdata <- read.csv("entropy.csv")
dim(entdata)
summary(entdata)
names(entdata)
str(entdata)
dim(entdata)


weights <- information.gain(buys_computer~., entdata)
print(weights)
subset <- cutoff.k(weights, 4)
f <- as.simple.formula(subset, "buys_computer")
print(f)

weights <- gain.ratio(buys_computer~., entdata)
print(weights)
subset <- cutoff.k(weights, 2)
f <- as.simple.formula(subset, "buys_computer")
print(f)
weights <- symmetrical.uncertainty(buys_computer~., entdata)
print(weights)
subset <- cutoff.biggest.diff(weights)
f <- as.simple.formula(subset, "buys_computer")
print(f)